# nutriwork:eat/fruit_low  (generated by tools/scaffold.ps1; safe to edit)
scoreboard players operation #amt nw.calc = #val_low nw.const
scoreboard players set #tag nw.calc 3
function nutriwork:core/monotony
scoreboard players operation @s nw.fruits += #amt nw.calc
execute if score @s nw.fruits matches 101.. run scoreboard players set @s nw.fruits 100
scoreboard players operation @s nw.fr_fruit = #window nw.const
function nutriwork:core/after_eat
advancement revoke @s only nutriwork:eat/fruit_low