# nutriwork:eat/grain_high  (generated by tools/scaffold.ps1; safe to edit)
scoreboard players operation #amt nw.calc = #val_high nw.const
scoreboard players set #tag nw.calc 7
function nutriwork:core/monotony
scoreboard players operation @s nw.grains += #amt nw.calc
execute if score @s nw.grains matches 101.. run scoreboard players set @s nw.grains 100
scoreboard players operation @s nw.fr_grain = #window nw.const
function nutriwork:core/after_eat
advancement revoke @s only nutriwork:eat/grain_high