# nutriwork:eat/protein_med  (generated by tools/scaffold.ps1; safe to edit)
scoreboard players operation #amt nw.calc = #val_med nw.const
scoreboard players set #tag nw.calc 11
function nutriwork:core/monotony
scoreboard players operation @s nw.protein += #amt nw.calc
execute if score @s nw.protein matches 101.. run scoreboard players set @s nw.protein 100
scoreboard players operation @s nw.fr_protein = #window nw.const
function nutriwork:core/after_eat
advancement revoke @s only nutriwork:eat/protein_med