# nutriwork:eat/sugar_low  (generated by tools/scaffold.ps1; safe to edit)
scoreboard players operation #amt nw.calc = #val_low nw.const
scoreboard players set #tag nw.calc 15
function nutriwork:core/monotony
scoreboard players operation @s nw.sugar += #amt nw.calc
execute if score @s nw.sugar matches 101.. run scoreboard players set @s nw.sugar 100
scoreboard players operation @s nw.fr_sugar = #window nw.const
function nutriwork:core/after_eat
advancement revoke @s only nutriwork:eat/sugar_low