# nutriwork:eat/veg_med  (generated by tools/scaffold.ps1; safe to edit)
scoreboard players operation #amt nw.calc = #val_med nw.const
scoreboard players set #tag nw.calc 5
function nutriwork:core/monotony
scoreboard players operation @s nw.veg += #amt nw.calc
execute if score @s nw.veg matches 101.. run scoreboard players set @s nw.veg 100
scoreboard players operation @s nw.fr_veg = #window nw.const
function nutriwork:core/after_eat
advancement revoke @s only nutriwork:eat/veg_med